rd /s /q ".vs"
rd /s /q "ipch"
rd /s /q "Debug"
rd /s /q "x64"
rd /s /q "ARM"
rd /s /q "obj"
rd /s /q "DTAR_08E86330_4835_4B5C_9E5A_61F37AE1A077_DTAR"
Del /q "Compiler.Cpp.sdf"
rd /s /q "Compiler\ARM"
rd /s /q "Compiler\Debug"
rd /s /q "Compiler\Generated Files"
rd /s /q "Compiler\x64"
Del /q "Compiler\Compiler.vcxproj.user"
Del /q "Compiler.CS.sdf"
rd /s /q "Compiler\bin"
rd /s /q "Compiler\obj"
Del /q "Compiler\Compiler.csproj.user"
rd /s /q "CompilerWRC\Generated Files"
rd /s /q "CompilerWRC\x64"
rd /s /q "CompilerWRC\ARM"